### ISSUE TITLE
Switch to onionoo as data source

### ISSUE THREAD

**Issue by nusenu** [kargig/tormap#1]
tormap currently uses raw consensus data that does not include any location information, based on the IP and maxmind data the location is determined.

[onionoo](https://metrics.torproject.org/onionoo.html) provides the same and much more data (it also uses maxmind for geoip location).
Switching to onionoo and exposing the used parameters would make tormap much more powerful since users could submit queries to only display a specific subset of relays they are interested in.
Examples: 
 * Display [UbuntuCore](https://medium.com/@nusenu/is-this-a-ubuntu-based-botnet-deploying-tor-relays-and-bridges-b4ce1a612039) or [default](https://atlas.torproject.org/#search/default) named relays only
 * Display only outdated relays
 * Display only relays from a given AS
 * Display only relays that run a specific version
onionoo has countless possibilities

**Comment by kargig** [comment]
I've switched to onionoo parsing in https://github.com/kargig/tormap/tree/onionoo_json. https://tormap.void.gr currently runs on this branch. If it's good enough for you I will merge this into master.

There's currently no support for custom user queries, this would need a complete rewrite of the script and a conversion to a python application accepting user input. The change is quite big so it's worth a different issue than the current one (switching to onioonoo as a source).

**Comment by nusenu** [comment]
thank you for working on this, two comments:

* looks like ContactInfo is not properly encoded so they are not properly shown if they have <> signs
* policy is currently displayed as a python dictionary

**Comment by kargig** [comment]
- can you provide a nickname of a relay with problematic ContactInfo ?
- policy printing format is fixed (and I also added IPv6 policy)

**Comment by nusenu** [comment]
George Kargiotakis:
> - can you provide a nickname of a relay with problematic ContactInfo ?

https://atlas.torproject.org/#details/9D30B15EC4979711AAD8C4B0A622B50B5B6EFDB5

**Comment by kargig** [comment]
this one is not shown because 'running' is set to false in onionoo. I've selected to display only the running=true ones. I could easily change this if needed
